### ISSUE TITLE
Enable or Disable plugin

### ISSUE THREAD

**Issue by dkdue** [rr222cy/ValheimPlus-Manager#11]
I have updated valheimplus to version 0.9.4 from the ValheimPlusManager application and when I click the button to deactivate it, it gives me an error
![image](https://user-images.githubusercontent.com/3610768/110213406-2bd24600-7ea0-11eb-81e5-837518f1d670.png)

**Comment by roos-robert** [comment]
Hi @dkdue and thanks for the bug report!

Have you previously disabled the mod by tampering with the "winhttp.dll" file? In that case, is the file named "winhttp.dll" as of now or have been renamed to something different?

Also, are you using the default installation path for Steam games or a custom one (on another drive for example)?

**Comment by dkdue** [comment]
I have not modified anything, I have only updated your application and then I have updated valheimplus, then I have tried to deactivate the plugin and it no longer left me

**Comment by roos-robert** [comment]
Alright! Can you verify that you have the "winhttp.dll" in the following directory "C:\Program Files (x86)\Steam\steamapps\common\Valheim"

I can't recreate the issue on my end so far.

**Comment by dkdue** [comment]
I have 2, in different ways
![image](https://user-images.githubusercontent.com/3610768/110214274-20811980-7ea4-11eb-94ec-e197b5b4db34.png)

**Comment by roos-robert** [comment]
Huh! Never seen this before, have you by chance used any other mods before?

Try to remove the "winhttp_.dll" and see if the disable button works. 😊

**Comment by dkdue** [comment]
I already have it clear, "winhttp_.dll" is to disable the plugin, and "winhttp.dll" enables it, it is already fixed, Thanks

**Comment by roos-robert** [comment]
Great! I can also confirm that in the upcoming 0.3.3 release this won't happen again as, if the file already exists it will be overwritten.

Thanks for reporting this!
