### ISSUE TITLE
Cannot insert negative values in the Wagon setting wagonExtraMassFromItems

### ISSUE THREAD

**Issue by PsyKoMari** [rr222cy/ValheimPlus-Manager#7]
First of all, good job with this GUI, I really appreciate it.
But I found a issue :blush:

The wagon settings include a wagonExtraMassFromItems

`; This value changes the game physical weight of Vagons by +/- more/less from item weight inside. The value 50 would increase the weight by 50% more. The value -100 would remove the entire extra weight.`

So the values can be in the range 50 to -100, in my configuration I wanted to set -50, but when I select the box in the GUI I cannot write the minus, only 50...
That's the opposite of what I want to do.

So I needed to set that value from the cfg file

**Comment by roos-robert** [comment]
Hi, thank you for the kind words and for reporting this bug!

I've corrected the issue and it will be fixed in the next release (0.3.1) that's coming hopefully later today (waiting for ValheimPlus 0.9.2). 😊

**Comment by PsyKoMari** [comment]
They jumped the 0.9.2 version :laughing:
They released directly the 0.9.3

**Comment by roos-robert** [comment]
Haha yeah I saw that, working on implementing the last of the changes as we speak then 0.3.1 will be released! :)
